name: awesome_flutter_map

environment:
  sdk: '^3.0.0'

dependencies:
  yaml: ^3.1.2
  pub_api_client: ^2.4.0
  pubspec: ^2.3.0
  intl: ^0.18.1
  pub_semver: ^2.1.4

dev_dependencies:
  total_lints: ^3.2.0
